# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2019 ANSSI. All rights reserved.

stages:
  - container
  - build

# Build CLIP OS
build:
  stage: build
  only:
    - master@CLIPOS/ci
  tags:
    - clipos
    - shell
  before_script:
    - ./download_artifacts.sh
  script:
    - ./build_clipos.sh
  after_script:
    - ./upload_artifacts.sh
    - ./cleanup.sh
  artifacts:
    when: always
    # Keep artifacts for 2 weeks by default so that we always have the last
    # Monday 'from scratch' build available for incremental builds.
    expire_in: 2 week
    paths:
      - artifacts/

# Build container image for QEMU image creation with libguestfs
# This should be triggered for a rebuild on a monthly basis.
container:
  stage: container
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CLIPOS_REBUILD_CONTAINER == "true"'
  tags:
    - clipos
    - shell
  script:
    - ./build_container_image.sh
