# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2019 ANSSI. All rights reserved.

stages:
  - container
  - build

# Build CLIP OS
build:
  stage: build
  only:
    - master@CLIPOS/ci
  tags:
    - clipos
    - shell
  script:
    - ./build_clipos.sh

# Build container image for QEMU image creation with libguestfs
# This should be triggered for a rebuild on a monthly basis.
container:
  stage: container
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
  tags:
    - clipos
    - shell
  script:
    - ./build_container_image.sh
