# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright © 2017 ANSSI. All rights reserved.

features = [
    "instrumented-core",
    "passwordless-root-login",
    "allow-ssh-root-login",
    #"dev-friendly-bootloader",
    "instrumented-initramfs",
    #"soften-kernel-configuration",
    "initramfs-no-require-tpm",
    "initramfs-no-tpm-lockout",
    #"debuggable-initramfs",
    #"breakpointed-initramfs",
    #"early-root-shell",
    #"debuggable-kernel",
    #"verbose-systemd",
    #"coredump-handler",
    #"test-update",
]

# vim: set ts=4 sts=4 sw=4 et ft=toml:
